version: '3.8'

services:
  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis_cache
    environment:
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: "redis_cache:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis_cache-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3